# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0012_auto_20151124_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='recycle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='study',
            name='unique_id',
            field=models.BooleanField(default=True),
        ),
    ]
